- hosts:
    - ec2-web
  become: yes
  vars:
    SERVER_NAME: ec2-52-196-175-139.ap-northeast-1.compute.amazonaws.com
    DOCUMENT_ROOT: /var/www/html
  roles:
    - common/server-settings
    - common/nginx
    - common/file-move